highlighter: rouge
permalink: /:title

url: "http://jonnyparris.github.io"
baseurl: ""

twitter_username: jonnyparris
github_username:  jonnyparris
description: "Ruskin's tech blog"

title: ruskindex.html
email: ruskin.constant@gmail.com


redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
